[behave]
# Default tags to skip
default_tags = -@xfail

# Console output formatting
default_format = pretty
show_skipped = false
format = behave_html_formatter:HTMLFormatter
outfiles = reports/TestExecutionReport.html
show_timings = true
color = true

# Paths
paths = tests/functional
step_paths = tests/functional/steps
environment_file = tests/functional/environment.py

# Reporting
junit = true
junit_directory = reports

# Logging
logging_level = INFO

[behave.formatters]
# HTML formatter alias
htmlreport = behave_html_formatter:HTMLFormatter